name: Docker Compose Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show project structure
        run: |
          ls -la
          ls -la backend
          ls -la frontend
          ls -la wiremock
          ls -la wiremock/mappings

      - name: Build and start services
        run: docker compose up --build -d

      - name: Wait for services
        run: sleep 60

      - name: Show running containers
        run: docker compose ps

      - name: Test WireMock not banned country
        run: curl -f http://localhost:8088/countries/ES

      - name: Test WireMock banned country
        run: curl -f http://localhost:8088/countries/VE

      - name: Test backend potential suppliers endpoint
        run: curl -f "http://localhost:8080/suppliers/potential?rate=1500000&limit=10&offset=0"

      - name: Test frontend
        run: curl -f http://localhost:3000

      - name: Show Docker logs on failure
        if: failure()
        run: docker compose logs

      - name: Stop services
        if: always()
        run: docker compose down -v